export const USER = {
  NUMBER_CONTROL_REPEAT_SAME_CHAR_ON_USERNAME: 8,
  ALLOWED_CHARACTERS_PASSWORD: 8,
  ALLOWED_NUMBERS_ON_PASSWORD: 3,
  ALLOWED_NUMBERS_IN_ROW_ON_PASSWORD: 2,
  ALLOWED_SPECIAL_CHARACTERS_ON_PASSWORD:
    /[`!@#$%^&*()_+\-=\[\]{};':"\\|,.<>\/?~]/,
  EMAIL_SYMBOL: "@",
};
